In [ ]:
# union of two sets
set1={1,2,3,4,5}
set2={6,7,8,9}
union_set=set1|set2
print(union_set)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
# intersection of two sets
set1={1,2,3,4,5}
set2={4,5,8,9}
intersection_set=set1 & set2
print(intersection_set)

{4, 5}


In [ ]:
# difference between two set
set1={1,2,3,4,5}
set2={4,5,8,9}
diff_set=set1 - set2
print(diff_set)

{1, 2, 3}


In [ ]:
#symetric
set1={1,2,3,4,5}
set2={4,5,8,9}
symetric_set=set1 ^ set2
print(symetric_set)

{1, 2, 3, 8, 9}


In [ ]:
#equal
set1={1,2,3,4,5}
set2={1,2,3,4,5}
equal_set=set1 == set2
print(equal_set)

True


In [14]:
import numpy as np
# 1d array
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [15]:
import numpy as np
# 2d array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
# array with evenly spaced value
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [18]:
# array with linear space value
import numpy as np
a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
# identity matrix
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# random array
import numpy as np
a=np.random.rand(3,3)
print(a)

[[0.12566648 0.05558047 0.60875709]
 [0.18512176 0.04651591 0.11473483]
 [0.69976932 0.57911952 0.66515453]]


In [24]:
# element wise addition
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.add(a,b)
print(c)

[5 7 9]


In [25]:
# elemente wise multiplication
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.multiply(a,b)
print(c)

[ 4 10 18]


In [27]:
# exponentiation
import numpy as np
a=np.array([1,2,3])
c=np.exp(a)
print(c)

[ 2.71828183  7.3890561  20.08553692]


In [28]:
# square root
import numpy as np
a=np.array([1,2,3])
c=np.sqrt(a)
print(c)

[1.         1.41421356 1.73205081]


In [30]:
# mean
import numpy as np
a=np.array([1,2,3])
c=np.mean(a)
print(c)


2.0


In [31]:
# median
import numpy as np
a=np.array([1,2,3])
c=np.median(a)
print(c)

2.0


In [32]:
# std daviation
import numpy as np
a=np.array([1,2,3])
c=np.std(a)
print(c)

0.816496580927726


In [34]:
# minimum and maximum
import numpy as np
a=np.array([1,2,3])
c=np.min(a)
print(c)
c=np.max(a)
print(c)



1
3


In [35]:
# 2d matrix multiplication
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.matmul(a,b)
print(c)


[[19 22]
 [43 50]]


In [36]:
# matrix inverse
import numpy as np
a=np.array([[1,2],[3,4]])
inv_a=np.linalg.inv(a)
print(inv_a)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
# random float
import numpy as np
a=np.random.rand()
print(a)

0.697952508400479


In [68]:
# random integer between 0 and 9
import numpy as np
a=np.random.randint(0,9)
print(a)

8
